config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "welcome#show"

  resources :recipes
  resources :meal_plans
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :meal_plan, inverse_of: :meals
  belongs_to :recipe
end

app/models/meal_plan.rb
class MealPlan < ApplicationRecord
  belongs_to :user
  has_many :meals, -> { order(:date) }, inverse_of: :meal_plan, dependent: :destroy

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :user, presence: true

  accepts_nested_attributes_for :meals

  def build_meals
    user_recipe_ids = user.recipes.pluck(:id)

    (start_date..end_date).each do |date|
      unused_recipe_ids = user_recipe_ids - meals.map(&:recipe_id)

      if unused_recipe_ids.empty?
        available_recipe_ids = user_recipe_ids
      else
        available_recipe_ids = unused_recipe_ids
      end

      meals.build(date: date, recipe_id: available_recipe_ids.sample)
    end
  end

  def to_s
    "#{I18n.localize(start_date)} - #{I18n.localize(end_date)}"
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user

  validates :name, presence: true, uniqueness: { scope: :user_id }
  validates :description, presence: true
  validates :user, presence: true

  def to_s
    name
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  has_many :recipes
  has_many :meal_plans

  def recipe_options
    recipes.map do |recipe|
      [recipe.name, recipe.id]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/meal_plans_controller.rb
class MealPlansController < ApplicationController
  before_action :require_login

  def index
    @current_meal_plan = current_user.meal_plans.where("start_date <= ? AND end_date >= ?", Date.today, Date.today).first
    @meal_plans = current_user.meal_plans.order("start_date DESC")
  end

  def show
    @meal_plan = current_user.meal_plans.find(params[:id])
    
  end

  def new
    @meal_plan = current_user.meal_plans.build(
      start_date: params[:start_date] || Date.today,
      end_date: params[:end_date] || 6.days.from_now.to_date,
    )
    @meal_plan.build_meals
  end

  def edit
    @meal_plan = current_user.meal_plans.find(params[:id])
  end

  def update
    @meal_plan = current_user.meal_plans.find(params[:id])

    if @meal_plan.update(meal_plan_params)
      redirect_to meal_plan_path(@meal_plan), notice: "Meal Plan Updated!"
    else
      @errors = @meal_plan.errors.full_messages
      render :edit
    end
  end

  def create
    @meal_plan = current_user.meal_plans.build(meal_plan_params)

    if @meal_plan.save
      redirect_to meal_plan_path(@meal_plan), notice: "Meal plan created!"
    else
      @errors = @meal_plan.errors.full_messages
      render :new
    end
  end

  def destroy
    @meal_plan = current_user.meal_plans.find(params[:id])
    @meal_plan.destroy
    redirect_to meal_plans_path, notice: "Deleted Meal Plan: #{@meal_plan}"
  end

  private

  def meal_plan_params
    params.require(:meal_plan).permit(
      :start_date,
      :end_date,
      meals_attributes: [
          :id,
          :date,
          :recipe_id,
      ]
    )
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :require_login

  def index
    @recipes = current_user.recipes.order(:id)
  end

  def show
    @recipe = current_user.recipes.find(params[:id])
  end

  def new
    @recipe = current_user.recipes.build
  end

  def create
    name_string = params["recipe"]["name"]
    name_with_spaces = name_string.parameterize(separator: '%20')
    response = HTTParty.get('https://api.edamam.com/api/recipes/v2?type=public&q=' + name_with_spaces + '&app_id=' + ENV["EDAMAM_APP_ID"] + '&app_key=' + ENV["EDAMAM_APP_KEY"])
    result = JSON.parse(response.body)
    parsed_ingredients = result['hits'][0]['recipe']['ingredientLines'].join("\n")
    parsed_url = result['hits'][0]['recipe']['url']
    @recipe = current_user.recipes.build(name: params["recipe"]["name"], description: parsed_ingredients + "\n\n" + parsed_url)
    if @recipe.save
      redirect_to recipe_path(@recipe), notice: "Recipe Created!"
    else
      @errors = @recipe.errors.full_messages
      render :new
    end
  end

  def edit
    @recipe = current_user.recipes.find(params[:id])
  end

  def update
    @recipe = current_user.recipes.find(params[:id])

    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe), notice: "Recipe Updated!"
    else
      @errors = @recipe.errors.full_messages
      render :edit
    end
  end

  def destroy
    recipe = current_user.recipes.find(params[:id])
    recipe.destroy
    redirect_to recipes_path, notice: "Deleted Recipe: #{recipe.name}"
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def show
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_class(flash_type)
    case flash_type.to_sym
    when :notice
      "alert-success"
    when :alert
      "alert-warning"
    when :error
      "alert-danger"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MealPlanner</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dangrek&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="container">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
          <%= link_to "MealPlanner", root_path, class: "navbar-brand" %>
          </div>

          <% if signed_in? %>
            <ul class="nav navbar-nav">
              <li><%= link_to "Meal Plans", meal_plans_path, class: "dashboard-button" %></li>
              <li><%= link_to "Recipes", recipes_path, class: "dashboard-button" %></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
              <li><%= button_to "Sign Out", sign_out_path, method: :delete, class: "dashboard-button" %>
            </ul>
          <% else %>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Sign In", sign_in_path, class: "dashboard-button" %></li>
              <li><%= link_to "Sign Up", sign_up_path, class: "dashboard-button" %></li>
            </ul>
          <% end %>
        </div>
      </nav>
    </header>

    <section class="container">
      <div id="flash">
        <% flash.each do |key, value| %>
          <div class="flash alert <%= alert_class(key) %>"><%= value %></div>
        <% end %>
      </div>
    <%= yield %>
    </section>
  </body>
</html>

app/views/meal_plans/_form.html.erb
<%= render partial: "shared/errors" %>

<%= form_for @meal_plan, html: { class: "form-horizontal" } do |form| %>
  <%= form.hidden_field :start_date %>
  <%= form.hidden_field :end_date %>

  <div class="meals">
    <%= form.fields_for :meals do |meal_fields| %>
      <%= meal_fields.hidden_field :id %>
      <%= meal_fields.hidden_field :date %>
      <div class="form-group margin-vertical-none">
        <div class="col-sm-11 col-sm-offset-1">
          <p><%= localize(meal_fields.object.date) %></p>
        </div>
      </div>

      <div class="form-group">
        <%= meal_fields.label :recipe_id, class: "col-sm-1 control-label"%>
        <div class="col-sm-11">
          <%= meal_fields.select :recipe_id, current_user.recipe_options, {}, class: "form-control" %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="form-group">
    <div class="col-sm-11 col-sm-offset-1">
      <%= form.submit class: "btn btn-primary"%>
    </div>
  </div>
<% end %>

app/views/meal_plans/edit.html.erb
<div class="title-container">
  <h1>Edit Meal Plan <%= @meal_plan %></h1>
</div>

<%= render partial: "form" %>

app/views/meal_plans/index.html.erb
<div class="title-container">
  <h1>Meal Plans</h1>
</div>

<% if @current_meal_plan.present? %>
  <h2>Current Meal Plan</h2>
  <div>
    <ul class="meals">
      <% @current_meal_plan.meals.each do |meal| %>
        <li class="meal">
          <%= localize(meal.date) %> - <%= link_to meal.recipe, recipe_path(meal.recipe) %>
        </li>
      <% end %>
    </li>
  </div>
<% end %>

<h3>All Meal Plans</h3>
<% @meal_plans.each do |meal_plan| %>
  <div class="meal-plan">
    <%= link_to meal_plan, meal_plan_path(meal_plan) %>
  </div>
<%end%>

<div class="actions">
  <%= link_to "New Meal Plan", new_meal_plan_path, class: "new-meal-plan-link" %>
</div>

app/views/meal_plans/new.html.erb
<div class="title-container">
  <h1>New Meal Plan</h1>
</div>

<div class="panel panel-default">
  <div class= "panel-body">
    <%= form_for @meal_plan, url: new_meal_plan_path, method: "GET", html: { class: "form-inline" } do |form| %>
      <div class="form_group">
        <%= form.label :start_date %>
        <%= form.text_field :start_date, type: "date", class: "form-control" %>
      </div>

      <div class="form_group">
        <%= form.label :end_date %>
        <%= form.text_field :end_date, type: "date", class: "form-control" %>
      </div>

      <div class="form-group action">
        <%= form.submit "Generate Plan", class: "btn btn-default"%>
      </div>
    <% end %>
  </div>
</div>

<%= render partial: "form" %>

app/views/meal_plans/show.html.erb
<div class="title-container">
  <h1>Meal Plan: <%= @meal_plan %></h1>
</div>

<ul class="meals">
  <% @meal_plan.meals.each do |meal| %>
    <li class="meal">
      <%= localize(meal.date) %> - <%= link_to meal.recipe, recipe_path(meal.recipe) %>
    </li>
  <% end %>
</ul>

<div class="actions">
  <ul class="meal-plan-actions">
    <li><%= link_to "Edit Meal Plan", edit_meal_plan_path(@meal_plan) %></li>
    <li><%= button_to "Delete", meal_plan_path(@meal_plan), method: :delete %></li>
  </ul>
</div>

app/views/recipes/_form.html.erb
<%= render partial: "shared/errors" %>

<%= form_for @recipe do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<div class="title-container">
  <h1>Edit Recipe</h1>
</div>

<%= render partial: "form" %>

app/views/recipes/index.html.erb
<div class="title-container">
  <h1>Recipes</h1>
  <%= link_to "New Recipe", new_recipe_path, class: "btn btn-default" %>
</div>

<div class="recipes">
  <% @recipes.each do |recipe| %>
    <div class="recipe">
      <div class="thumbnail">
        <div class="caption">
          <h3><%= link_to truncate(recipe.name), recipe_path(recipe), class: "recipe-title-in-recipes" %></h3>
          <p><%= truncate(recipe.description, length: 150) %></p>
          <p>
            <%= link_to "Edit", edit_recipe_path(recipe), class: "btn btn-default" %></li>
            <%= button_to "Delete", recipe_path(recipe), method: :delete %></li>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/recipes/new.html.erb
<div class="title-container">
  <h1>New Recipe</h1>
</div>

<%= render partial: "form" %>

app/views/recipes/show.html.erb
<div class="title-container">
  <h1><%= @recipe.name %></h1>
</div>

<h2>Description</h2>
<p><%= simple_format @recipe.description, class: "recipe-description" %></p>

<div>
  <ul class="recipe-actions">
    <li><%= link_to "Back", recipes_path %></li>
    <li><%= link_to "Edit", edit_recipe_path(@recipe) %></li>
    <li><%= button_to "Delete", recipe_path(@recipe), method: :delete %></li>
    </ul>
</div>

app/views/shared/_errors.html.erb
<% if @errors.present? %>
  <div class="alert alert-danger errors">
    <ul>
      <% @errors.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email, class: "form" %>
  <%= form.email_field :email, class: "input" %>
</div>

<div class="password-field">
  <%= form.label :password, class: "form" %>
  <%= form.password_field :password, class: "input" %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <div class="sign-up-box">
    <h4><%= t(".title") %></h4>
  </div>
  <div class="sign-up-form">
    <%= form_for @user do |form| %>
      <%= render partial: '/users/form', object: form %>

      <div class="submit-field">
        <%= form.submit %>
      </div>

      <div class="other-links">
        <%= link_to t(".sign_in"), sign_in_path %>
      </div>
    <% end %>
  </div>
</div>

app/views/welcome/show.html.erb
<div class="welcome-sign">
  <h1 class="special-welcome">Welcome to MealPlanner!</h1>
  <h1>Click sign in or sign up to begin.</h1>
</div>